name: Build and Push Ubuntu-rust-gtk4

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "Dockerfile.ubuntu-rust-gtk4"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: amd64
            arch: amd64
          - platform: arm64
            arch: arm64v8

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push for ${{ matrix.platform }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.ubuntu-rust-gtk4
          platforms: linux/${{ matrix.platform }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-rust-gtk4:${{ matrix.platform }}
          build-args: |
            ARCH=${{ matrix.arch }}
          provenance: false

  merge:
    needs: build-and-push
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create and push multi-arch manifest
        run: |
          docker manifest create ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-rust-gtk4:latest \
            ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-rust-gtk4:amd64 \
            ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-rust-gtk4:arm64
          docker manifest annotate ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-rust-gtk4:latest \
            ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-rust-gtk4:amd64 --arch amd64
          docker manifest annotate ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-rust-gtk4:latest \
            ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-rust-gtk4:arm64 --arch arm64
          docker manifest push ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-rust-gtk4:latest

      - name: Check push
        run: |
          docker buildx imagetools inspect ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-rust-gtk4:latest
